# Generated by Django 2.1.15 on 2020-04-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qanda',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='qanda',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='created_at',
        ),
    ]
