# Generated by Django 2.1.15 on 2020-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sweetpotato_num',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
