# Generated by Django 2.1.15 on 2020-04-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200417_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='korean_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
