# Generated by Django 2.1.15 on 2020-04-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_korean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sweetpotato_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
